# 统一 Cargo 产物目录
[build]
target-dir = "hanpet/src-tauri/target"
incremental = true

[profile.dev]
opt-level = 0
debug = 1
incremental = true
codegen-units = 256
split-debuginfo = "unpacked"

[profile.test]
inherits = "dev"
debug = 1

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
