use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let root = manifest_dir.join("..");
    let roster = root.join("bundled/roster");
    let template = root.join("bundled/pet-action-template.json");
    let prompts = root.join("bundled/prompts");

    for sub in ["characters", "personas", "pet-models"] {
        println!("cargo:rerun-if-changed={}", roster.join(sub).display());
    }
    println!("cargo:rerun-if-changed={}", template.display());
    println!("cargo:rerun-if-changed={}", prompts.display());

    generate_embedded(&roster, &template, &prompts).expect("generate embedded resources");
}

fn generate_embedded(roster: &Path, template: &Path, prompts_dir: &Path) -> std::io::Result<()> {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("embedded.rs");
    let mut f = fs::File::create(&out_path)?;

    let characters_manifest = roster.join("characters/manifest.json");
    let personas_manifest = roster.join("personas/manifest.json");

    writeln!(f, "// @generated by build.rs — do not edit\n")?;
    writeln!(
        f,
        "pub const CHARACTERS_MANIFEST: &str = include_str!(r\"{}\");",
        characters_manifest.display()
    )?;
    writeln!(
        f,
        "pub const PERSONAS_MANIFEST: &str = include_str!(r\"{}\");",
        personas_manifest.display()
    )?;
    writeln!(
        f,
        "pub const PET_ACTION_TEMPLATE: &str = include_str!(r\"{}\");",
        template.display()
    )?;

    write_persona_embeds(&mut f, &roster.join("personas"))?;
    write_prompt_embeds(&mut f, prompts_dir)?;
    write_builtin_models(&mut f, roster)?;

    Ok(())
}

fn write_prompt_embeds(f: &mut fs::File, prompts_dir: &Path) -> std::io::Result<()> {
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if prompts_dir.is_dir() {
        for entry in fs::read_dir(prompts_dir)? {
            let entry = entry?;
            if !entry.file_type()?.is_file() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();
            let Some(stem) = name.strip_suffix(".md") else {
                continue;
            };
            if stem.eq_ignore_ascii_case("readme") {
                continue;
            }
            entries.push((stem.to_string(), entry.path()));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    writeln!(f, "pub const EMBEDDED_PROMPTS: &[(&str, &str)] = &[")?;
    for (id, path) in &entries {
        writeln!(
            f,
            "    (\"{id}\", include_str!(r\"{}\")),",
            path.display()
        )?;
    }
    writeln!(f, "];")?;
    Ok(())
}

fn write_persona_embeds(f: &mut fs::File, personas_dir: &Path) -> std::io::Result<()> {
    let mut md_entries: Vec<(String, PathBuf)> = Vec::new();
    let mut json_entries: Vec<(String, PathBuf)> = Vec::new();

    if personas_dir.is_dir() {
        for entry in fs::read_dir(personas_dir)? {
            let entry = entry?;
            if !entry.file_type()?.is_file() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().to_string();
            let Some(stem) = name.strip_suffix(".md") else {
                if let Some(stem) = name.strip_suffix(".json") {
                    if stem != "manifest" {
                        json_entries.push((stem.to_string(), entry.path()));
                    }
                }
                continue;
            };
            md_entries.push((stem.to_string(), entry.path()));
        }
    }
    md_entries.sort_by(|a, b| a.0.cmp(&b.0));
    json_entries.sort_by(|a, b| a.0.cmp(&b.0));

    writeln!(f, "pub const EMBEDDED_PERSONAS_MD: &[(&str, &str)] = &[")?;
    for (id, path) in &md_entries {
        writeln!(
            f,
            "    (\"{id}\", include_str!(r\"{}\")),",
            path.display()
        )?;
    }
    writeln!(f, "];")?;

    writeln!(f, "pub const EMBEDDED_PERSONAS_JSON: &[(&str, &str)] = &[")?;
    for (id, path) in &json_entries {
        writeln!(
            f,
            "    (\"{id}\", include_str!(r\"{}\")),",
            path.display()
        )?;
    }
    writeln!(f, "];")?;
    Ok(())
}

fn write_builtin_models(f: &mut fs::File, roster: &Path) -> std::io::Result<()> {
    let names = model_display_names(&roster.join("characters/manifest.json"))?;
    let models_dir = roster.join("pet-models");

    writeln!(f, "pub struct BuiltinModelDef {{")?;
    writeln!(f, "    pub id: &'static str,")?;
    writeln!(f, "    pub name: &'static str,")?;
    writeln!(f, "    pub skel: &'static str,")?;
    writeln!(f, "    pub atlas: &'static str,")?;
    writeln!(f, "    pub png: &'static str,")?;
    writeln!(f, "    pub meta_json: &'static str,")?;
    writeln!(f, "}}")?;

    writeln!(f, "pub static BUILTIN_MODELS: &[BuiltinModelDef] = &[")?;

    if models_dir.is_dir() {
        let mut ids: Vec<String> = fs::read_dir(&models_dir)?
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .collect();
        ids.sort();

        for id in ids {
            let model_dir = models_dir.join(&id);
            let Some(triple) = spine_triple_from_config(&model_dir) else {
                continue;
            };
            let name = names.get(&id).cloned().unwrap_or_else(|| id.clone());
            let meta_path = model_dir.join("animations.meta.json");
            if !meta_path.is_file() {
                continue;
            }
            writeln!(f, "    BuiltinModelDef {{")?;
            writeln!(f, "        id: \"{id}\",")?;
            writeln!(f, "        name: \"{name}\",")?;
            writeln!(f, "        skel: \"{}\",", triple.0)?;
            writeln!(f, "        atlas: \"{}\",", triple.1)?;
            writeln!(f, "        png: \"{}\",", triple.2)?;
            writeln!(
                f,
                "        meta_json: include_str!(r\"{}\"),",
                meta_path.display()
            )?;
            writeln!(f, "    }},")?;
        }
    }

    writeln!(f, "];")?;
    Ok(())
}

fn model_display_names(manifest_path: &Path) -> std::io::Result<std::collections::HashMap<String, String>> {
    use std::collections::HashMap;
    let mut map = HashMap::new();
    let Ok(raw) = fs::read_to_string(manifest_path) else {
        return Ok(map);
    };
    let Ok(v) = serde_json::from_str::<serde_json::Value>(&raw) else {
        return Ok(map);
    };
    let Some(chars) = v.get("characters").and_then(|c| c.as_array()) else {
        return Ok(map);
    };
    for ch in chars {
        let name = ch.get("name").and_then(|n| n.as_str()).unwrap_or("");
        let Some(skins) = ch.get("skins").and_then(|s| s.as_array()) else {
            continue;
        };
        for skin in skins {
            if let Some(model_id) = skin.get("model_id").and_then(|m| m.as_str()) {
                map.insert(model_id.to_string(), name.to_string());
            }
        }
    }
    Ok(map)
}

fn spine_triple_from_config(model_dir: &Path) -> Option<(String, String, String)> {
    let cfg_path = model_dir.join("config.json");
    let raw = fs::read_to_string(&cfg_path).ok()?;
    let v: serde_json::Value = serde_json::from_str(&raw).ok()?;
    let skel = v.get("skeleton")?.as_str()?.to_string();
    let atlas_entry = v.get("atlases")?.as_array()?.first()?;
    let atlas = atlas_entry.get("atlas")?.as_str()?.to_string();
    let png = atlas_entry
        .get("textures")?
        .as_array()?
        .first()?
        .as_str()?
        .to_string();
    if model_dir.join(&skel).is_file()
        && model_dir.join(&atlas).is_file()
        && model_dir.join(&png).is_file()
    {
        Some((skel, atlas, png))
    } else {
        None
    }
}
