"""Thin re-export surface for roster.ids (impl in roster.db)."""
from __future__ import annotations

from roster import db as _db

SKIN_SUFFIX = getattr(_db, 'SKIN_SUFFIX')
LATIN_RE = getattr(_db, 'LATIN_RE')
CJK_RE = getattr(_db, 'CJK_RE')
LIVE2D_ALIASES = getattr(_db, 'LIVE2D_ALIASES')
ALIAS_PRIMARY_BY_CN = getattr(_db, 'ALIAS_PRIMARY_BY_CN')
SHIP_CODE_ID = getattr(_db, 'SHIP_CODE_ID')
HASH_PERSONA_ID = getattr(_db, 'HASH_PERSONA_ID')
is_ship_code_id = getattr(_db, 'is_ship_code_id')
normalize_character_id = getattr(_db, 'normalize_character_id')
preferred_slug_for_cn = getattr(_db, 'preferred_slug_for_cn')
enrich_alias_map_from_roster = getattr(_db, 'enrich_alias_map_from_roster')
alias_redirect_id = getattr(_db, 'alias_redirect_id')
dedupe_characters_by_name = getattr(_db, 'dedupe_characters_by_name')
strip_skin = getattr(_db, 'strip_skin')
is_folder_like_character_id = getattr(_db, 'is_folder_like_character_id')
skin_label = getattr(_db, 'skin_label')
is_generic_wiki_skin_label = getattr(_db, 'is_generic_wiki_skin_label')
is_hidden_wiki_skin = getattr(_db, 'is_hidden_wiki_skin')
is_oath_skin_id = getattr(_db, 'is_oath_skin_id')
clean_cv = getattr(_db, 'clean_cv')
pick_english = getattr(_db, 'pick_english')
pick_skin_title = getattr(_db, 'pick_skin_title')
is_hx_skin = getattr(_db, 'is_hx_skin')
skin_db_id = getattr(_db, 'skin_db_id')
skin_manifest_id = getattr(_db, 'skin_manifest_id')
normalize_name_en = getattr(_db, 'normalize_name_en')
_stable_wiki_id = getattr(_db, '_stable_wiki_id')
_parse_id_filter = getattr(_db, '_parse_id_filter')
_parse_import_phases = getattr(_db, '_parse_import_phases')
